### ISSUE TITLE
Add an example involving range types

### ISSUE THREAD

**Issue by lelit** [CanopyTax/asyncpgsa#12]
I have a table like the following:

```
CREATE TABLE users (
  id SERIAL,
  name VARCHAR(15),
  active DATERANGE,

  PRIMARY KEY (id)
)
```

that with plain SQLAlchemy+psycopg2 I can query with:

```
    today = date.today()
    q = select([users.c.id]) \
        .where(users.c.name == 'test') \
        .where(users.c.active.contains(today))
    r = session.execute(q)
```

With the following asyncpgsa transliteration:

```
    today = date.today()
    q = sa.select([users.c.id]) \
        .where(users.c.name == 'test') \
        .where(users.c.active.contains(today))
    r = await pg.fetchrow(q)
```

I get an error:

```
/usr/local/lib/python3.5/site-packages/asyncpgsa/pgsingleton.py:65: in fetchrow
    return await conn.fetchrow(query, *args, timeout=timeout)
/usr/local/lib/python3.5/site-packages/asyncpgsa/connection.py:91: in fetchrow
    result = await self.connection.fetchrow(query, *params, *args, **kwargs)
/usr/local/lib/python3.5/site-packages/asyncpg/connection.py:259: in fetchrow
    False, timeout)
asyncpg/protocol/protocol.pyx:157: in bind_execute (asyncpg/protocol/protocol.c:45856)
    ???
asyncpg/protocol/prepared_stmt.pyx:122: in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg (asyncpg/protocol/protocol.c:42239)
    ???
asyncpg/protocol/codecs/base.pyx:123: in asyncpg.protocol.protocol.Codec.encode (asyncpg/protocol/protocol.c:12276)
    ???
asyncpg/protocol/codecs/base.pyx:90: in asyncpg.protocol.protocol.Codec.encode_range (asyncpg/protocol/protocol.c:11868)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: list, tuple or Range object expected (got type <class 'datetime.date'>)

asyncpg/protocol/codecs/range.pyx:53: TypeError
```

which seems odd to me: what I want is to test whether a single date is within a period...

I tried the following code, passing a one-item-tuple instead:

```
    today = date.today()
    q = sa.select([users.c.id]) \
        .where(users.c.name == 'test') \
        .where(users.c.active.contains((today,)))
    r = await pg.fetchrow(q)
```

that works, but that seems to convert the argument to a [today, +infinity] range, something different from what I'm seeking.

What am I missing?

**Comment by lelit** [comment]
For the history, the following seems a workaround:
```python
today = date.today()
q = sa.select([users.c.id]) \
    .where(users.c.name == 'test') \
    .where(users.c.active.contains(sa.func.daterange(today, today, '[]')))
r = await pg.fetchrow(q)
```

**Comment by nhumrich** [comment]
Sorry, didnt notice this issue until now. Can I see your sqlalchemy definition of your `users` table?

**Comment by lelit** [comment]
Sure, here is a minimalistic but complete example:
```python
import asyncio
import datetime

from sqlalchemy import select, Table, Column, Integer, UnicodeText, MetaData
import sqlalchemy.dialects.postgresql as sapg
from asyncpgsa import pg

# CREATE TABLE users (
#     id serial,
#     name text,
#     active daterange
# );
# INSERT INTO users (name, active) VALUES ('myself', '[2016-10-21,2016-10-22)');

metadata = MetaData()
users = Table('users', metadata,
    Column('id', Integer(), primary_key=True),
    Column('name', UnicodeText()),
    Column('active', sapg.DATERANGE()),
)

async def main(loop):
    await pg.init(
        host='localhost',
        port=5432,
        database='test_issue12',
        loop=loop,
        min_size=5,
        max_size=10,
    )

    query = 'select * from users'
    async with pg.query(query) as cursor:
        async for row in cursor:
            print(row)

    date = datetime.date(2016, 10, 21)
    query = select([users.c.name]).where(users.c.active.contains(date))
    async with pg.query(query) as cursor:
        async for row in cursor:
            print(row)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
```

that emits the following output:
```
<Record id=1 name='myself' active=<Range [datetime.date(2016, 10, 21), datetime.date(2016, 10, 22))>>
Traceback (most recent call last):
  File "issue12.py", line 45, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/local/python3.6/lib/python3.6/asyncio/base_events.py", line 449, in run_until_complete
    return future.result()
  File "/usr/local/python3.6/lib/python3.6/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "issue12.py", line 40, in main
    async for row in cursor:
  File "/tmp/e/lib/python3.6/site-packages/asyncpgsa/pgsingleton.py", line 133, in __anext__
    return Record(await self.iterator.__anext__())
  File "/tmp/e/lib/python3.6/site-packages/asyncpg/cursor.py", line 175, in __anext__
    buffer = await self._bind_exec(self._prefetch, self._timeout)
  File "/tmp/e/lib/python3.6/site-packages/asyncpg/cursor.py", line 96, in _bind_exec
    self._state, self._args, self._portal_name, n, True, timeout)
  File "asyncpg/protocol/protocol.pyx", line 155, in bind_execute (asyncpg/protocol/protocol.c:46368)
  File "asyncpg/protocol/prepared_stmt.pyx", line 122, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg (asyncpg/protocol/protocol.c:42751)
  File "asyncpg/protocol/codecs/base.pyx", line 123, in asyncpg.protocol.protocol.Codec.encode (asyncpg/protocol/protocol.c:12615)
  File "asyncpg/protocol/codecs/base.pyx", line 90, in asyncpg.protocol.protocol.Codec.encode_range (asyncpg/protocol/protocol.c:12207)
  File "asyncpg/protocol/codecs/range.pyx", line 53, in asyncpg.protocol.protocol.range_encode (asyncpg/protocol/protocol.c:31368)
TypeError: list, tuple or Range object expected (got type <class 'datetime.date'>)
```

**Comment by nhumrich** [comment]
This one is interesting. It looks like the logic for converting datetimes into ranges lies inside of psycopg2. Im not really sure a good way to handle this. You could try filling an issue for asyncpg and see if they will convert python objects into postgres ones, but the best solution is probably to do the conversion yourself.

**Comment by lelit** [comment]
I already did that (see [asyncpg#32](https://github.com/MagicStack/asyncpg/issues/32)), but the issue has been closed basically as _unresolvable_. I guess that psycopg2 simply pass the argument to PG, and then the polymorphic behaviour of the operator takes place.

**Comment by nhumrich** [comment]
I think psycopg2 does some python type conversion for you. Which is one of the reasons is slower. It has to introspect every non-std object

**Comment by rbcarson** [comment]
I hit this same issue and found success with casting the argument: `sqlalchemy.cast(date, sqlalchemy.Date)`. This then works as expected with `contains()`, and with `CAST($1 AS DATE)` being the result in SQL.

**Comment by lelit** [comment]
FYI, I was finally able to spin-off my slightly different implementation from a proprietary application, released as [metapensiero.sqlalchemy.asyncpg](https://pypi.python.org/pypi/metapensiero.sqlalchemy.asyncpg).
