### ISSUE TITLE
TypeError: object of type 'Select' has no len()

### ISSUE THREAD

**Issue by valentinmk** [CanopyTax/asyncpgsa#28]
Well, I take this as example 
```
import asyncio
import asyncpgsa

import sqlalchemy as sa
pg_tables = pg_tables = sa.Table(
        'pg_tables', sa.MetaData(),
        sa.Column('schemaname'),
        sa.Column('tablename'),
        sa.Column('tableowner'),
        sa.Column('tablespace'),
        sa.Column('hasindexes')
    )

async def main():
    pool = await asyncpgsa.create_pool(
        host=?,
        port=?,
        database=?,
        user=?,
        # loop=event_loop,
        password="5800149687",
        min_size=5,
        max_size=10,
        max_inactive_connection_lifetime=60, # What is it? Why its mandatory?
    )
    query = pg_tables.select().where(pg_tables.c.schemaname == 'pg_catalog')
    async with pool.acquire() as conn:
        for row in await conn.fetch(query):
            a = row.col_name


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

and get this: 
```
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    loop.run_until_complete(main())
  File "/home/valentin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "test.py", line 32, in main
    for row in await conn.fetch(query):
  File "/home/valentin/.pyenv/versions/tesla-much/lib/python3.6/site-packages/asyncpg/connection.py", line 340, in fetch
    return await self._execute(query, args, 0, timeout)
  File "/home/valentin/.pyenv/versions/tesla-much/lib/python3.6/site-packages/asyncpg/connection.py", line 651, in _execute
    return await self._do_execute(query, executor, timeout)
  File "/home/valentin/.pyenv/versions/tesla-much/lib/python3.6/site-packages/asyncpg/connection.py", line 662, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/home/valentin/.pyenv/versions/tesla-much/lib/python3.6/site-packages/asyncpg/connection.py", line 276, in _get_statement
    len(query) > self._max_cacheable_statement_size):
TypeError: object of type 'Select' has no len()
```
I think that asyncpg was made some changes inside the code. Need workaround or fix or maybe I've made mistake some where.

**Comment by nhumrich** [comment]
Looks like you installed the latest version of asyncpg. This library should be locked to a specific version that it works with, so you should just use that in your requirements rather than upgrading to the latest asyncpg code.

**Comment by valentinmk** [comment]
Thank you, Nick. 
Lately, after I wrote this post, I found this in [dev-requirements.txt
](https://github.com/CanopyTax/asyncpgsa/blob/master/dev-requirements.txt).
It will be great to add `requirements` section in the readme.md (aka the first page), so nobody stuck like me.

**Comment by nhumrich** [comment]
I added a section in the readme to hopefully help mitigate this issue.
