### ISSUE TITLE
How to create the database using sqlalchemy's create_all ?

### ISSUE THREAD

**Issue by franckinux** [CanopyTax/asyncpgsa#37]
I found nowhere an example to create the database. Here is one of my tries 

```python
import asyncio
import os
import sys

import asyncpgsa
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

from model import Base
from utils import read_configuration_file


async def main(config, loop=None):
    if loop is None:
        loop = asyncio.get_event_loop()

    db_connection_infos = {
        "drivername": "postgres",
        "host": config["host"],
        "port": config["port"],
        "username": config["username"],
        "password": config["password"],
        "database": config["database"]
    }
    dsn = str(URL(**db_connection_infos))

    db_engine = await create_engine(dsn, echo=True, module=asyncpgsa)
    try:
        Base.metadata.create_all(db_engine)
    except:
        sys.stderr.write("cannot connect to database\n")
        sys.exit(2)
    finally:
        db_engine.dispose()


if __name__ == "__main__":
    config = read_configuration_file()
    if not config:
        sys.exit(1)
    config = config["database"]
    config["password"] = os.getenv("PG_PASS", "") or config["password"]

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(config))
```

The error is :

```
Traceback (most recent call last):
  File "create-schema.py", line 46, in <module>
    loop.run_until_complete(main(config))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "create-schema.py", line 28, in main
    db_engine = await create_engine(dsn, echo=True, module=asyncpg)
  File "/home/franck/projets/python/my-own-little-business/venv/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/franck/projets/python/my-own-little-business/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 88, in create
    dialect = dialect_cls(**dialect_args)
  File "/home/franck/projets/python/my-own-little-business/venv/lib/python3.5/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 521, in __init__
    PGDialect.__init__(self, **kwargs)
  File "/home/franck/projets/python/my-own-little-business/venv/lib/python3.5/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2083, in __init__
    default.DefaultDialect.__init__(self, **kwargs)
  File "/home/franck/projets/python/my-own-little-business/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 196, in __init__
    self.paramstyle = self.dbapi.paramstyle
AttributeError: module 'asyncpg' has no attribute 'paramstyle'
```

I also tried to use the _creator_ param of create_engine. Not better, the function beeing a coroutine, I fear sqlalchemy does not like this...

**Comment by nhumrich** [comment]
You cant use `create_engine` with this library. The engine is part of sqlalchemy ORM. This library only supports the core (query language). 

From canopy's experience, we only create databases using migrations (alembic) and so async doesnt matter. You could create databases using the core, by writing actual sql queries, but the higher level sqlalchemy things will not work.

**Comment by nhumrich** [comment]
Closing due to no activity
