### ISSUE TITLE
Unable to insert into a table with JSONB

### ISSUE THREAD

**Issue by alejandrorosas** [CanopyTax/asyncpgsa#43]
Hi,

Im facing some problems when I insert a JSONB into a table, I get this error:
```
following exception:  'StrCompileDialect' object has no attribute '_json_serializer'
Traceback (most recent call last):
  File "/Users/alejandrorosas/.pyenv/versions/raven/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 456, in _cached_bind_processor
    return dialect._type_memos[self]['bind']
  File "/Users/alejandrorosas/.pyenv/versions/3.6.2/lib/python3.6/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x10d9c54a8; to 'JSONB' at 0x10d91f2e8>
```

In the 0.14.2 version it was working correcly, maybe there's an issue with the latest version.

Thanks!

**Comment by nhumrich** [comment]
Interesting. Could you add a test case for this issue?

**Comment by nhumrich** [comment]
Interesting. Could you add a test case for this issue?

**Comment by achimnol** [comment]
Maybe related to my PR #42. I think `compiled._bind_processors` should do the necessary work here.

@alejandrorosas Could you please show the table schema (in SQLAlchemy Table definitions) and the Python code that performs your query?

**Comment by alejandrorosas** [comment]
yes @achimnol sorry for the delay, the schema is sth like:

```
custom_table = Table(
    'custom_table',
    metadata,
    Column('custom_id', Text, primary_key=True),
    Column('payload', JSONB),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=text("now()"))
)
```

and the query:
```
    async def insert_custom_table(self, custom_table_dict):
        async with self.pool.transaction() as conn:
            query = custom_table.insert().values(custom_table_dict)
            return await conn.fetchrow(query)
```

**Comment by Pehat** [comment]
I've just found [this](https://magicstack.github.io/asyncpg/current/usage.html#example-automatic-json-conversion) nice piece of documentation for asyncpg. Is there an underlying asyncpg connection I can modify this way?

**Comment by nhumrich** [comment]
@Pehat This just got merged, and shows how to do it:
https://github.com/CanopyTax/asyncpgsa/pull/78/files#diff-caf2a6b8f4947d018f68893c695b5202R254
