### ISSUE TITLE
pip failed to install package

### ISSUE THREAD

**Issue by vayw** [CanopyTax/asyncpgsa#60]
pip can't install **_asyncpgsa_** if it's part of requirements list alongside with **_asyncpg_** (in other words it requires _asyncpg_ to be installed before installing _asyncpgsa_). Is there a way to change version determination?
```
Collecting asyncpg==0.12.0 (from -r .meta/packages (line 5))
....
Collecting asyncpgsa==0.18.1 (from -r .meta/packages (line 6))
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gcdgh8ov/asyncpgsa/setup.py", line 6, in <module>
        version=__import__('asyncpgsa').__version__,
      File "/tmp/pip-build-gcdgh8ov/asyncpgsa/asyncpgsa/__init__.py", line 1, in <module>
        from .pool import create_pool
      File "/tmp/pip-build-gcdgh8ov/asyncpgsa/asyncpgsa/pool.py", line 3, in <module>
        import asyncpg
    ModuleNotFoundError: No module named 'asyncpg'
```

**Comment by nhumrich** [comment]
Cant reproduce. 
I installed in a brand new virtual env, and it installed asyncpg just fine.  Asyncpg should not need to be installed. Can you provide your packages file? 

```
$ pip freeze

$ pip install asyncpgsa 
Collecting asyncpgsa
  Using cached asyncpgsa-0.18.2-py3-none-any.whl
Collecting sqlalchemy (from asyncpgsa)
  Using cached SQLAlchemy-1.1.15.tar.gz
Collecting asyncpg~=0.12.0 (from asyncpgsa)
  Using cached asyncpg-0.12.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: sqlalchemy, asyncpg, asyncpgsa
  Running setup.py install for sqlalchemy ... done
Successfully installed asyncpg-0.12.0 asyncpgsa-0.18.2 sqlalchemy-1.1.15

$ pip freeze
asyncpg==0.12.0
asyncpgsa==0.18.2
SQLAlchemy==1.1.15
```

**Comment by Hardtack** [comment]
It happens to me when I try to install _asyncpgsa_ from the source like:
```bash
$ pip install git+git://github.com/CanopyTax/asyncpgsa.git#egg=asyncpgsa
Collecting asyncpgsa from git+git://github.com/CanopyTax/asyncpgsa.git#egg=asyncpgsa
  Cloning git://github.com/CanopyTax/asyncpgsa.git to /private/var/folders/r7/2vrf035j01gd8wn1_r0phlgm0000gn/T/pip-build-z8i7fz3c/asyncpgsa
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r7/2vrf035j01gd8wn1_r0phlgm0000gn/T/pip-build-z8i7fz3c/asyncpgsa/setup.py", line 6, in <module>
        version=__import__('asyncpgsa').__version__,
      File "/private/var/folders/r7/2vrf035j01gd8wn1_r0phlgm0000gn/T/pip-build-z8i7fz3c/asyncpgsa/asyncpgsa/__init__.py", line 1, in <module>
        from .pool import create_pool
      File "/private/var/folders/r7/2vrf035j01gd8wn1_r0phlgm0000gn/T/pip-build-z8i7fz3c/asyncpgsa/asyncpgsa/pool.py", line 3, in <module>
        import asyncpg
    ModuleNotFoundError: No module named 'asyncpg'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/r7/2vrf035j01gd8wn1_r0phlgm0000gn/T/pip-build-z8i7fz3c/asyncpgsa/
```

It occurs because, _setup.py_ try to import whole module even if dependencies are not installed yet.
