### ISSUE TITLE
Issues casting a parameter

### ISSUE THREAD

**Issue by mackeyja92** [CanopyTax/asyncpgsa#80]
Running the following query results in a traceback. Seems it cannot handle casting parameters.

```
sql = '''
    SELECT date::date 
    FROM generate_series(:start_month::date, :end_month::date, '1 month'::interval)
'''
now = datetime.datetime.now()
start_month = datetime.datetime(now.year, now.month, 1)
end_month = datetime.datetime(now.year, now.month + 1, 1)
query = sa.text(sql).params(start_month=start_month, end_month=end_month)
await conn.fetch(query)
```

```
Traceback (most recent call last):
...
  File "/python3.6/site-packages/asyncpgsa/connection.py", line 99, in _execute
    query, compiled_args = compile_query(query, dialect=self._dialect)
  File "/python3.6/site-packages/asyncpgsa/connection.py", line 83, in compile_query
    params = _get_keys(compiled)
  File "/python3.6/site-packages/asyncpgsa/connection.py", line 52, in _get_keys
    raise MissingParameterError('Parameter {} missing'.format(e))
asyncpgsa.connection.MissingParameterError: "Parameter 'start_month' missing"
```

**Comment by vmagamedov** [comment]
It is actually SQLAlchemy cannot handle PostgreSQL-specific casting syntax:
```python
>>> sqlalchemy.text("SELECT :foo::INTEGER;").params(foo="1").compile().params
{}
```
But this works:
```python
>>> sqlalchemy.text("SELECT CAST(:foo AS INTEGER);").params(foo="1").compile().params
{'foo': '1'}
```
And asyncpgsa also will work this way:
```python
>>> compile_query(sqlalchemy.text("SELECT CAST(:foo AS INTEGER);").params(foo="1"))
('SELECT CAST($1 AS INTEGER);', ['1'])
```
